MakePrisms/agicash

src/hooks/useCashu.ts

- added pwa configuration (#35)
- add qrcode scanner for sending to bolt11 (#37)
- update pwa loga & change manifest name (#39)
- add qr codes back to sendecashmodal (#40)
- change pwa name
- process invoice right after scan
- More pwa updates (#42)
- change theme color
- bug fix: get proofs only for active wallet keyset
- Scan QR to receive tokens (#44)
- add transaction history + ability to reclaim unspent tokens (#45)
- .
- force baalnce update in `swapToSend`

Correctly set balance when sending tokens

---

src/components/ActivityIndicator.tsx
src/components/buttons/lightning/Receive.tsx
src/hooks/useCashu.ts

show an error if requesting mint invoice fails. likely due to mint being offline or minting being disabled

handle fail to request mint

---

src/pages/already-running.tsx
src/pages/wallet.tsx

only allow one tab to be open

---

src/components/sidebar/ConnectReserveSetting.tsx
src/hooks/useNostrMintConnect.ts

Fetch and display backend balance and mint balance under reserve settings

add reserve metrics to nmc

---

src/components/EcashTapButton.tsx
src/components/modals/ConfirmEcashReceiveModal.tsx
src/components/sidebar/MintSidebarItem.tsx
src/contexts/cashuContext.tsx
src/hooks/useCashu2.ts
src/hooks/useNostrMintConnect.ts
src/hooks/useProofStorage.tsx
src/pages/_app.tsx
src/pages/wallet.tsx

Refactored the places where proofs are handled to be more logical and safe

Improve proof management w/ `useProofStorage` hook/context

---

src/components/sidebar/Reserve/ConnectReserve.tsx
src/components/sidebar/Reserve/ConnectReserveSetting.tsx
src/components/sidebar/SettingsSidebar.tsx
src/hooks/useNwa.ts

Connect to Alby with one click via NWA

Get NWC with nostr wallet auth ([nip 67](https://github.com/benthecarman/nips/blob/nostr-wallet-connect-connect/67.md))

---

src/components/modals/ConfirmEcashReceiveModal.tsx
src/hooks/cashu/useCashu.ts

patch: fix "Error when claiming from other mint"

---

src/hooks/cashu/useCashu.ts

Cross mint swaps were not working for locked tokens, now they do

unlock tokens before melting them

---

prisma/migrations/20240811012034_mint_quote_token/migration.sql
prisma/schema.prisma
src/components/buttons/LightningTipButton.tsx
src/lib/mintQuoteModels.ts
src/pages/[slug].tsx
src/pages/api/invoice/polling/[slug].ts
src/pages/api/tip/[slug].ts
src/pages/api/tip/status.ts
src/styles/globals.css
src/types.ts
src/utils/appApiRequests.ts
src/utils/formatting.ts

adds an "eTip" button that allows anyone with a Lightning wallet to pay directly tip this boardwalk user.

Lightning eTips on profile page

---

src/components/buttons/LightningTipButton.tsx
src/components/buttons/Receive.tsx
src/components/buttons/Send.tsx
src/components/modals/SendEcashModal.tsx
src/components/modals/SendEcashModalBody.tsx
src/components/modals/SendModal.tsx
src/components/sidebar/Mints/AddMintButton.tsx
src/components/sidebar/Mints/SetMainButton.tsx
src/components/sidebar/Mints/SwapToMainButton.tsx
src/pages/setup.tsx
src/pages/wallet.tsx
src/styles/globals.css

Applies `btn-primary` class to all primary buttons and fixes that class a bit

btn-primary styling + misc

---

src/components/eGifts/GiftModal.tsx
src/components/eGifts/ViewGiftModal.tsx
src/components/modals/SendEcashModalBody.tsx
src/components/modals/WaitForInvoiceModal.tsx
src/pages/[slug].tsx
src/scripts/addDefaultGifts.js
src/styles/globals.css
tailwind.config.ts

When state changes occured sometimes the hover button would appear as though it was clicked on mobile. Now it just stays the same color when clicked or hovered

don't have a hover color on clipboard button

---

src/components/buttons/LightningTipButton.tsx
src/components/buttons/Receive.tsx
src/components/eGifts/GiftModal.tsx
src/components/modals/WaitForInvoiceModal.tsx
src/hooks/util/useExchangeRate.tsx
src/pages/api/invoice/polling/[slug].ts
src/pages/api/tip/[pubkey].ts
src/utils/appApiRequests.ts
src/utils/convertToUnit.ts

makes the profile page work for sats and usd

fix profile page for multi-currency

---

src/components/modals/SendModal.tsx
src/hooks/cashu/useCashu.ts
src/types.ts

Improve `InsufficientBalanceError` msg

---

src/pages/setup.tsx

Closes https://github.com/MakePrisms/boardwalkcash/issues/126

Change btc mints url on setup page not to filter USD mints only

---

src/components/buttons/Receive/ReceiveFlow.tsx
src/components/buttons/Send/AmountInput.tsx
src/components/buttons/Send/InputOptions.tsx
src/components/buttons/Send/Lud16Input.tsx
src/components/buttons/Send/SendButton.tsx
src/components/buttons/Send/SendFlow.tsx
src/components/views/ConfirmAndPayPaymentRequest.tsx
src/components/views/QRScanner.tsx

The idea was to pull that out from the AmountInput and Lud16Input, but most of the props just get passed through, and with this initial approach I had to overwrite disableNext and onNext because that logic is different based on whether its an amount or lud16 input.

refactor send flow

---

src/hooks/contexts/cashuContext.tsx
src/redux/slices/UserSlice.ts

Closes https://github.com/MakePrisms/boardwalkcash/issues/125

Make btc the default currency of the wallet

---

src/components/transactionHistory/HistoryTableRow.tsx

Another attempt to fix Awayuki's account.
In the future we should change the date prop on transactions to be a unix timestamp #156

add error handling to formatDate

---

src/components/buttons/Send/SendFlow.tsx

While processing the input this will make the Continue button have a spinner

set isProcessing = true on send paste

---

bolt11-decoder.d.ts
package-lock.json
package.json
src/components/buttons/Send/SendFlow.tsx
src/components/modals/WaitForInvoiceModal.tsx
src/components/views/WaitForLightningInvoicePayment.tsx
src/hooks/boardwalk/useMintlessMode.ts
src/hooks/nostr/useNwc.ts
src/lib/mintQuoteModels.ts
src/lib/nip47Processors.ts
src/utils/bolt11.ts
src/utils/cashu.ts

Updated the light-bolt11-decoder packager, so now we have better typing. 
Replaced the getAmountAndExpiryFromInvoice and getAmountFromInvoice with decodeBolt11

improve the bolt11 decoding function

---

src/components/views/SelectGift.tsx

fix desktop styles for ConfirmSendToGift

---

src/components/transactionHistory/HistoryTable.tsx
src/components/transactionHistory/HistoryTableRow.tsx
src/components/views/SelectContact.tsx
src/components/views/ViewReusablePaymentRequest.tsx
src/components/views/WaitForEcashPayment.tsx

fixed a bug with eGifts not showing up properly in tx history and made some minor style changes

Style fix: contact, qr, tx history

---

GUIDELINES.md

A working document to keep track of project structure and principals we should follow. Mostly generated by LLM based on discord messages and my current project structure.
Having something like this will help me figure out what to do when adding new code

add GUIDELINES

---

app/components/redirect.tsx
app/lib/transitions/view-transition.tsx
app/routes/_auth.tsx
app/routes/_protected.tsx
app/routes/_protected.verify-email.($code).tsx

I noticed that we can simplify the redirects a bit

Refactor redirects to use component

---

app/routes/_protected._index.tsx

reverts [this](https://github.com/MakePrisms/boardwalkcash/pull/223/files#diff-23279a07afc0af74e94f0c134562908ef6dc7668aad191d6d195925ca266229fR185) diff

revert bad rebase from merging #223

---

.github/workflows/ci.yml
app/components/money-display.tsx
app/lib/money/money.ts
app/lib/money/types.ts
app/routes/_protected._index.tsx
e2e/login.spec.ts

Here is alternative approach that I find more readable.
I think that this component should be kept only for displaying input value. For places where we don't have input involved we can have a simpler presentational component

Alternative proposal for money input display

---

.github/workflows/ci.yml
app/components/money-display.tsx
app/lib/money/money.ts
app/lib/money/types.ts
app/routes/_protected._index.tsx
e2e/login.spec.ts

Creates two components for rendering money. One is MoneyInputDisplay that has special formatting based on the string value the user has input, and the other is MoneyDisplay which is used for simply rendering Money (ie. balances)

add component to display money

---

app/features/settings/settings.tsx
app/features/signup/upgrade-guest-form.tsx
app/routes/_protected._index.tsx

The main thing I did here is created an upgrade-guest-form component and then moved that to settings.
I also cleaned up the home page a bit, but this is not meant to be a finished product it was just getting messy. I left the "Welcome to Boardwalk!" and "Log Out" button so that the tests still pass because I think we will continue changing this page so I don't want to chase the tests every time for now.

move upgrade to guest form to settings and cleanup homepage

---

app/components/numpad.tsx
app/hooks/use-number-input.ts
app/lib/money/index.ts
app/lib/money/money.test.ts
app/lib/money/utils.ts

I wasn't sure whether to make this a utility function or a static method on `Money`. I chose a utility function inside the money lib because it's related to money, but not directly and doesn't do anything with the actual Money class. All this does is tell us the decimal separator for a locale.
We could move it to the Money class and then have some extra functionality for different units so we would know whether that unit should even have a decimal separator or not. 'sat' would return null for example.
what do you think?

create getLocaleDecimalSeperator function

---

app/features/receive/receive-cashu.tsx
app/features/receive/use-mint-quote.ts

Refactor based on comments in #252

refactor receive cashu and quote hook

---

app/features/accounts/account-hooks.ts
app/features/accounts/account-repository.ts
app/features/receive/cashu-receive-quote-repository.ts
app/features/receive/cashu-receive-quote.ts
app/features/shared/cashu.ts
app/features/shared/encryption.ts
app/features/user/user-hooks.tsx
app/features/user/user-repository.ts

Alternative approach where we pass encryption functions to repos via constructor vs individually when invoking functions.
We can now compare and decide what we like better

Inject encryption to repos via constructor

---

app/features/accounts/account-hooks.ts
app/features/accounts/account.ts
app/features/receive/cashu-receive-quote-service.ts
app/features/receive/cashu-token-swap-hooks.ts
app/features/receive/cashu-token-swap-service.ts
app/features/receive/receive-cashu-token-hooks.tsx
app/features/receive/receive-cashu-token.tsx
app/lib/utils.ts

I added handling for fees and some debug logs for debugging race conditions

Handle fees for cashu token swap

---

app/features/accounts/account-cryptography.ts
app/features/shared/cashu.ts
app/features/shared/encryption.ts
bun.lock
package.json

Derives 12 words seed phrases for cashu accounts

upgrad OS and use bip85 for cashu seeds

---

app/components/ui/scroll-area.tsx
app/features/settings/accounts/add-mint-form.tsx
app/features/settings/accounts/all-accounts.tsx
app/tailwind.css
bun.lock
package.json

The main thing here is the feature validation in `app/features/settings/accounts/add-mint-form.tsx`.
I also made some UI updates to the account list

validate mint's supported features

---

app/features/receive/cashu-receive-quote-repository.ts
app/features/receive/cashu-receive-quote-service.ts
app/features/receive/cashu-receive-quote.ts
app/features/send/cashu-send-quote-repository.ts
app/features/send/cashu-send-quote.ts
app/features/transactions/transaction.ts
supabase/database.types.ts
supabase/migrations/20250428082111_add-transactions.sql

I added transaction entity plus I updated cashu-receive-quote and cashu-send-quote db functions to create and manage related transaction state

Transactions

---

app/routes/_protected._index.tsx
e2e/helpers.ts
e2e/login.spec.ts
e2e/signup.spec.ts
e2e/verify-email.spec.ts

I removed the "Log Out" and "Welcome to Boardwalk" from the home screen so I had to update the tests.

clean up home page and update tests

---

app/features/settings/accounts/$account_id.tsx

I made it so we always render divs with a static height whether the content inside is rendered or not. This way if no content is rendered the layout stays static

make account page layout static when setting default

---

app/features/settings/profile/editable-username.tsx

- auto-select username text when editing the profile name
- `bun run lint:check`
- `bun run format:check`
- `bun run typecheck`

Implement username auto-select on edit

---

supabase/migrations/20250503202924_cashu-send-swaps.sql

- refine `complete_cashu_send_swap` and `complete_cashu_token_swap` using project guidelines
- index `cashu_send_swaps.transaction_id` for quick lookup during reversal
- `bun run fix:all`
- `bun test`
- `bun run test:e2e` *(fails: Docker not running)*

Update send/receive swap completion

---

app/features/accounts/account-hooks.ts
app/features/send/cashu-send-quote-hooks.ts
app/features/send/cashu-send-quote-repository.ts
app/features/send/cashu-send-quote-service.ts
app/features/send/cashu-send-quote.ts
app/features/send/cashu-send-swap-service.ts
app/features/send/send-confirmation.tsx
app/features/send/send-input.tsx
app/features/send/send-provider.tsx
app/features/send/send-store.ts
app/features/send/succesful-send-page.tsx
app/features/shared/error.ts
app/lib/cashu/utils.ts
app/routes/_protected.send.share.$swapId.tsx
supabase/database.types.ts
supabase/migrations/20250605114151_updates-to-send-quotes.sql

Closes https://github.com/MakePrisms/boardwalkcash/issues/371

Don't initiate ln sends if balance is not sufficient

---

.gitignore
README.md
app/features/agicash-db/database.ts
app/server.ts
app/supabase-proxy.ts
bun.lock
devenv.nix
package.json
tools/devenv/generate-ssl-cert.sh

Here is the approach with proxy. To run the app with https you now need to do `bun run dev --https`
This should work on all devices

Setup https for local development

---

app/features/receive/cashu-receive-quote-hooks.ts
bun.lock
package.json
vite.config.ts

Fixes https://github.com/MakePrisms/boardwalkcash/issues/464

Fetch mint info bug fix

---

app/features/shared/encryption.ts
app/features/wallet/wallet.tsx

@gudnuf we are now suspending the app to fetch the data encryption key from OS. The key is then cached until the app is reloaded. Everything else works the same. Seems to be working fine.

Use local data encryption

---

app/features/receive/cashu-token-swap-hooks.ts
app/features/receive/cashu-token-swap-service.ts
app/features/send/cashu-send-swap-hooks.ts

This is the second part of temporary concurrency improvements that handles send and receive swaps.

Improve concurrency error handling for swaps

---

app/components/ui/drawer.tsx
app/components/ui/toast.tsx
app/features/accounts/account-selector.tsx
app/features/accounts/default-currency-switcher.tsx
app/features/contacts/add-contact-drawer.tsx
app/features/send/send-input.tsx
app/features/settings/settings.tsx
tailwind.config.ts

there was a slight delay before when toasts and drawers would get dismissed. They would slide until almost out of view then stick for a fraction of a second before disappearing completely

unstick toasts and drawers

---

app/features/receive/cashu-receive-quote-repository.ts
app/features/receive/cashu-token-swap-repository.ts
app/features/receive/cashu-token-swap-service.ts
app/features/send/cashu-send-quote-repository.ts
app/features/send/cashu-send-quote-service.ts
app/features/send/cashu-send-swap-repository.ts
app/features/shared/encryption.ts
app/features/transactions/transaction-details.tsx
app/features/transactions/transaction-hooks.ts
app/features/transactions/transaction-repository.ts
app/features/transactions/transaction.ts
supabase/database.types.ts
supabase/migrations/20250722221908_encrypt-transaction-amounts-and-details.sql

drops the amount column from transactions and adds details that get encrypted.
Trying out my first commit copied the db functions and then the second commit makes updates to them

Encrypted tx details

---

supabase/migrations/20250730211555_update-create-receive-quote.sql

two commits: 
1. copies the old function
2. modifies it so you can see easier

Set pending cross mint receives

---

app/features/settings/settings.tsx
app/features/settings/ui/settings-nav-button.tsx
app/features/theme/color-mode-toggle.tsx

settings ui updates

---

bun.lock
package.json

Don't think we need anything from the latest release but bumped it anyway

Upgrade open secret sdk

---

app/features/signup/verify-email.ts
app/features/user/user-hooks.tsx
app/routes/_protected.tsx
app/routes/_protected.verify-email.($code).tsx
react-router.config.ts

This should give us additional speed up in some scenarios. See https://remix.run/blog/split-route-modules for details

Enable route module splitting

---

app/features/transactions/transaction-list.tsx

While debugging other bugs I noticed that we are triggering bunch of duplicate requests to read transactions on the history page. 
It was because `onEndReached` method had a different instance on each render and we didn't use useLatest. Since that prop was a dep of useEffect that registers intersection observer, it was recreating observer all the time. Additionaly because in effect cleanup we are doing:
```
if (ref.current) {
observer.unobserve(ref.current);
}
```
cleanup never worked and we were ending up with more and more observers being created which caused duplicate requests. The reason why unobserve didn't work is because when react runs the cleanup dom is already unmounted so ref.current is null. That's why I used useLayoutEffect instead because it runs before the dom is unmounted. …

Transactions infinite scroll bug fix

---

app/features/receive/receive-cashu-token-hooks.tsx
app/features/receive/receive-cashu-token.tsx

feedback for #620

---

app/features/agicash-db/database.ts

This will help me debug the realtime connection issues that we are having.

Setup logger for supabase realtime

---

app/root.tsx
bun.lock
package.json
patches/@sentry%2Fcore@10.14.0.patch

I believe this might solve the issue with Sentry logs showing weird timestamps.

Patch sentry sdk

---

app/lib/supabase/supabase-realtime-manager.ts

Will add one more retry first without any delay

Small improvement
