- src/components/sidebar/MintSidebarItem.tsx
This adds a badge next the mints that are marked `isReserve: true`
> tag reserves in mint list

- src/components/buttons/lightning/Receive.tsx
- src/components/icons/ClockIcon.tsx
- src/components/icons/XMarkIcon.tsx
- src/components/modals/SendModal.tsx
- src/components/transactionHistory/TransactionHistoryDrawer.tsx
Before, lgithning transactions were getting added as pending, and then if they ailed, the pending payments still looked liked a success. Now, the lightining payments only get added to tx history when they are completed
> Only show successful lightning txes in history

- src/components/buttons/lightning/Receive.tsx
Currently, stablenut.umint.cash mint does not work with lightning address due to exchange rate issues. Stablenut is the main usd mint, so we disable lightning address for now until a solution arises
> Remove lightning address

- global.d.ts
Adds a function to `computeTxId` that creates a unique identifier for token, no matter the order of the proofs.
- NOTE: this is not part of the nuts
Stores tokens in the database by txid
Lookup tokens (including from a sharable link) by txid
> add transaction IDs

- src/utils/url.ts
if the user typed in a url with uppercase then this would break fetching the mint info
> conver mint urls to lowercase

- src/components/transactionHistory/HistoryTableRow.tsx
This is my attempt to fix the gift error Bob pointed out
The date should never be undefined, but when I search the codebase for 'split' this is the only thing that makes sense.
> check if date is undefined

- src/hooks/contexts/cashuContext.tsx
- src/lib/mintModels.ts
This should solve the problem of the mint keyset not being found when a mint that hasn't been seen before is added. 
To test, clear your local database and your browser storage, then refresh and add a mint. Now try to mint some ecash and it should work without toggling mints.
> make sure keysets get created for new mints

- src/hooks/cashu/useCashu.ts
There was a potential loss of funds from the time that `createSendableToken` was called to when the calling function completed sending if, for example, the user refreshed the page while the sendable proofs were only in memory.
I attempted to resolve this by storing the freshly created proofs back in localstorage, then removing them once they are either spent or saved elsewhere (ie. transaction history or database)
> make `getProofsToSend` more robust to refreshes

- src/components/ToggleCurrencyDropdown.tsx
- src/hooks/contexts/cashuContext.tsx
Fixes a bug where if the user's main sat account is their NWC, then `defaultWallets.has(Currency.SAT)` returns false and does not let the user toggle to BTC mode.
> allow toggle if `nwcIsMain`

- src/hooks/cashu/useCashu.ts
- src/hooks/cashu/usePaymentRequests.ts
If paying the invoice failed, then we would still try to mint tokens which would throw an error and then the error messages were confusing. Now we just fail as soon as paying the invoice fails
> Don't try to mint tokens if failed to pay payment request invoice

- src/pages/setup.tsx
Depending on the browser, sometimes the continue button at the bottom of the warning page would not show up. This ensures there is plenty of padding below so that the user can scroll all the way down and click continue﻿
> fix padding for mobile on setup page

- src/pages/wallet.tsx
A simple solution to check pending lightning transactions when the app loads. I only put `loadingState` in the dependency array because I do not want this run every time history.lightning changes.
> check pending mint quotes on load

- src/components/buttons/Receive/ReceiveFlow.tsx
- src/components/views/ViewReusablePaymentRequest.tsx
- src/hooks/cashu/usePaymentRequests.ts
- src/hooks/util/usePolling.ts
- src/lib/paymentRequestModels.ts
- src/pages/api/token/pr/[id]/index.ts
- src/pages/api/token/pr/[id]/last-paid.ts
- src/types.ts
When the ViewReusablePaymentRequest view is open it will poll the /pr/[id]/last-paid endpoint. This endpoint returns the token that was most recently sent to that payment request.
When the view opens, we store the most recent request in `lastPaid`. If a token is created after that time and the view is still open then we claim the token and close the view.
In use polling I added a check for `timeout`. If `timeout` is undefined it will poll until unmounted.
> poll reusable payment requests

- src/lib/mintQuoteModels.ts
- src/utils/bolt11.ts
- src/utils/cashu.ts
I assumed that the expiry on the invoice was the absolute timestamp, but its actually relative to the timestamp. To correctly get the expiry we add it to the timestamp of the invoice﻿
> fix bug when calculating invoice expiry

- src/hooks/cashu/useCashu.ts
I had wrongly assumed that cashu-ts would create change outputs for any overpaid amount put into the library. What the library actually does is create outputs only for fees (see attached pic). To fix it I reverted a change I had made in #123 that removed what I thought was an unnecessary swap. Now we will swap for the exact amount of ecash before melting. This creates an unnecessary swap, but prevents loss of funds. It looks like in cashu-ts V2 this is fixed (see [here](https://github.com/cashubtc/cashu-ts/blob/development/src/CashuWallet.ts#L755))
> revert to  swapping before melting

- src/pages/wallet.tsx
initializeUser is not called﻿ when the user has not set up boardwalk and they are viewing a gift link, so we need to check if the user.status is 'idle' to setLoading(false) otherwise the page will say 'Loading...' forever when a user that has never visited boardwalk clicks on a sharable link
> set loading false if user not setup boardwalk

- src/utils/nostr.ts
nostr-tools got updated and made this breaking change. nip19.decode used to return a string, now it returns a Uint8Array when the data is an nsec
> convert decoded nsec from Uint8Array

- src/pages/_app.tsx
- src/pages/index.tsx
- src/pages/wallet.tsx
- src/utils/url.ts
Get the domain of the requested app so that the gifts and preview image urls resolve to the deployment being used.
Falls back to https://boardwalkcash.com
> set base path for open graph requests

- src/pages/api/users/username/[username]/index.ts
- src/pages/api/users/username/[username]/token.ts
- src/utils/cashu.ts
- src/utils/convertToUnit.ts
- src/utils/error.ts
I added a new endpoint: `/api/users/username/[username]/token.ts`. 
I'm making it so that OpenTollGate (the wifi router you pay with ecash) can accept tokens and pay to a Boardwalk user.
Now anyone can send a token directly to a Boardwalk user without directly supporting cashu using a script like this:
```bash
#!/bin/sh
BOARDWALK_ENDPOINT="https://boardwalk-git-feat-post-token-makeprisms.vercel.app"
token=$1
boardwalk_username=$2
response=$(curl -s -w "%{http_code}" -X POST -H "Content-Type: application/json" -d "{\"token\": \"$token\"}" "$BOARDWALK_ENDPOINT/api/users/username/$boardwalk_username/token")
echo "$response"
http_code=$(echo "$response" | tail -c 4)
body=$(echo "$response" | head -c -4)
if [ "$http_code" != "200" ]; then
error_msg=$(echo "$body" | grep -o '"error":"[^"]*"' | …
```
> POST token to Boardwalk username

- app/components/ui/button.tsx
- biome.jsonc
Use useSortedClasses to improve readability of tailwind class lists. Adapted the [tailwind recommend IDE setup](https://tailwindcss.com/docs/editor-setup) to use biome instead of prettier
Please see [the biome docs](https://biomejs.dev/linter/rules/use-sorted-classes/). They say this is considered an "unsafe" feature. I marked it as safe in our biome config so that it gets auto-fixed. I assume it's unsafe just because it's still "in the nursery" ie. beta, but let me know what you think about auto-fixing based on what they say in the docs about it. All that it does is reorder classes lists based on some heuristic
> add class sorting to biome config

- app/components/money-display.tsx
- app/routes/_protected._index.tsx
Here I added a `MoneyDisplay` component that is used just for display `Money` without doing any padding of zeros.
I also removed the sizes form the MoneyInputDisplay to your point [in this comment](https://github.com/MakePrisms/boardwalkcash/pull/257/files#r1901362945)
> simple presentational money display component

- supabase/config.toml
config.toml settings are not applied to master env after all. see screenshot:
My initial understanding that for persistent branches we need to configure [remotes] might have been correct. Testing that here
> Configure live Supabase env via config file.

- app/components/money-display.tsx
I got rid of the size option and made the sizes based on the variant. 
Right now we always have a  big amount on top and then the converted amount below that is smaller and different colors.
Another option would be to have color variants separate from sizes, but that seems unnecessary right now.
> makes default and secondary variants for MoneyDisplay

- app/features/receive/receive-cashu-token.tsx
- app/features/receive/use-receive-cashu-token.tsx
This gets rid of our loading state and makes the hook a bit cleaner because now in the second query we only need to return the claimableToken.
I'm not sure how the suspense query works exactly, but it seems that the tokenData query does not run until the sourcAcountData query has returned a value  which also makes things simpler
I also removed `value` and `canClaim` from the return data of the hook.
> useSuspenseQuery in useReceiveCashuToken

- app/components/ui/carousel.tsx
Tested on iPhone SE size and 0.5 works, but if I go smaller on the width then that doesn't work so I did 0.3 to be safe
> decrese onPresented carousel threshold to 0.3

- app/features/accounts/account-hooks.ts
- app/features/receive/cashu-receive-quote-hooks.ts
- app/features/receive/cashu-token-swap-hooks.ts
I solved it by adding a separate cache for latest known account versions and then when we get a notification of account being updated we update the latest known account version in this new cache and only then start decrypting the account data. Then when someone wants to read the latest account from the cache they can do it by calling getLatest on the accounts cache and that will now wait for the data to be updated if it detects the version in the versions cache being bigger than the version in the accounts cache.
It goes something like this:
1. accounts cache: [{ id: `q1w2`, version: `1` }], versions cache for `q1w2` account: `1` (at this point version cache is actually empty but when reading from the empty cache it will return the version from the accounts cache so effectively it is `1`) …
> Handle swap cashu token race condition

- app/features/settings/profile/edit-profile.tsx
- app/features/settings/profile/editable-username.tsx
- app/features/settings/profile/upgrade-guest-form.tsx
- app/features/settings/settings.tsx
- app/features/user/user-hooks.tsx
- app/features/user/user-repository.ts
- app/features/user/user.ts
- app/hooks/use-animation.ts
- supabase/database.types.ts
- supabase/migrations/20250416224601_add-username-to-user-table.sql
- tailwind.config.ts
Adds username to the user table. 
There is a trigger that fires before the user is inserted that gives the user a default username. The call to insert the user is made -> then the trigger function is ran -> user gets inserted -> user is returned with the default username value.
And I updated `upsert_user_with_accounts` to return the username along with the rest of the user.
You can now see your username in `/settings` and edit your username at `/settings/profile/edit`
NOTE: I still need to fix the tailwind issue...
> add editable usernames

- app/features/receive/cashu-receive-quote-hooks.ts
- app/features/receive/cashu-receive-quote-repository.ts
- app/features/receive/cashu-receive-quote-service.ts
- app/features/receive/cashu-receive-quote.ts
- app/features/shared/cashu.ts
- app/features/shared/cryptography.ts
- app/features/shared/encryption.ts
- bun.lock
- package.json
- supabase/database.types.ts
- supabase/migrations/20250508000000_add_locking_derivation_path.sql
Uses nut20 signed mint quotes instead of encrypting the mint quote id
- store quote id as plaintext in the db
- create mint quotes locked to a public key
- include a signature on the quote when minting proofs
- fixed `getSeed` to correctly get the mnemonic and then convert that to a seed instead of using the extended key
- I separated the private keys and signing functions out of the useEncryption hook and made a useCryptography hook because those things aren't encryption related
> use signed mint quotes instead of encrypting quote ID

- app/features/boardwalk-db/database.server.ts
- app/features/boardwalk-db/database.ts
- app/features/receive/cashu-receive-quote-repository.ts
- app/features/receive/cashu-receive-quote-service.ts
- app/features/receive/lightning-address-service.tsx
- app/features/settings/profile/share-profile-qr.tsx
- app/features/shared/cashu.ts
- app/features/user/user-hooks.tsx
- app/features/user/user-repository.ts
- app/features/user/user.ts
- app/lib/lnurl/types.ts
- app/routes/[.]well-known.lnurlp.$username.ts
- app/routes/api.lnurlp.callback.$user_id.ts
- app/routes/api.lnurlp.verify.$cashu_receive_quote_id.ts
- supabase/database.types.ts
- supabase/migrations/20250422235033_add-cashu-xpubs-to-user.sql
Depends on #350 because we need the NUT20 signed mint quotes.
This gives all our users a lightning address at user@example.domain
This adds 3 routes all defined by the [LUDs](https://github.com/lnurl/luds/tree/luds):
- `.well-known/lnurlp/<username>` - to get the lnurlp params from a lightning address
- `api/lnurlp/callback/<user_id>` - to get the invoice to pay
- `api/lnurlp/verify/<payment_id>` - to verify the payment status of an invoice
I added a cashuLockingXpub to users when they are upserted, and this is then used in the `LightningAddressService` to create a `CashuReceiveQuote` locked to a public key the user controls. When the user is online, we detect the new receive quote and finish the receive flow.
> implement lightning address receives

- app/features/receive/cashu-receive-quote-hooks.ts
Latest receive quotes were not being fetched on load because initial date in the query was set
> fix pendingCashuReceiveQuote query fetching

- app/features/user/user-hooks.tsx
this is what was causing our user id to chnage when upgrade guest occurred. We were using the wrong function.
> bug fix: convert guest instead of signup guest

- app/features/receive/cashu-receive-quote-service.ts
The CashuReceiveQuoteService.completeReceive function can be called multiple times and if we don't use the stored counter and outputAmount values when the quote is PAID, then when we try to recover already issued proofs we might be using the wrong values and not be able to restore.
> bug fix: use counter and outputAmounts from quote if set

- app/features/accounts/account-hooks.ts
I noticed that currently we are currently using accounts cache in "background work" stuff and we expect the accounts to be loaded into cache without anything actually making sure to load them. This causes an error to be thrown if you directly try to open a page that doesn't call useAccounts. E.g. try opening http://localhost:3000/settings/appearance and see what happens.
To make sure accounts are always loaded I added a call to useAccounts inside the useTrackAccounts hook that is called from the wallet component. This means that every wallet route will now have accounts loaded before any other work starts
> Make sure accounts are loaded into cache in the wallet component

- app/features/accounts/default-currency-switcher.tsx
- app/features/wallet/wallet.tsx
If you switched default currency on another device, then returned to original device the default currency would get updated, but our theme colors are read from cookies and the cookies were not being updated
> sync ui theme with default currency

- app/features/accounts/account-hooks.ts
- app/features/receive/receive-cashu-token-hooks.tsx
Sometimes a token from a different wallet would be from a mint we already had added, but the urls did not match exactly. Now when we decode the token we normalize the url and also normalize urls when we take them from our database.
There was also a bug where the receive account was not read from selectable accounts, so we were not including the badges there. We want the receive account to have badges too so they show in the selector.
> receive-cashu-token: normalize mint urls and fix badges

- app/components/search-bar.tsx
- use `LoaderCircle` icon for search bar loading state
- `bun run test` *(fails: Cannot find packages)*
> Fix search bar spinner visibility

- app/lib/transitions/view-transition.tsx
- store transition data in navigation state when using `useNavigateWithViewTransition`
- `bun test`
- `bun run test:e2e` *(fails: Docker not running)*
> Fix view transition state with programmatic navigation

- app/features/receive/receive-cashu-token-hooks.tsx
- app/features/transactions/transaction-list.tsx
- biome.jsonc
This PR has two commits:
1. enables the useHookAtTopLevel in biome config which checks that hooks are not rendered inside conditionals (that should never be done as hooks rely on consistent ordering across renders to function normally) and fixes one offending case in transaction history list where we had a hook used after early returns
2. Fixes issue with signup as guest and claim token flow for case where the token being claimed belongs to the default account. The issue was that in this flow we first show public page where `useCashuTokenSourceAccountQuery` hook is used but without existing account and the result gets cached. Then when guest account is created and default accounts added, the hook gets executed again but this time with existing account, but since the result was cached with …
> Signup as guest and claim bug fix

- app/features/send/share-cashu-token.tsx
Adds a share button that shows the devices native share interface so that you can easily text or airdrop shareable links
> add share button to share-cashu-token

- app/features/receive/cashu-token-swap-service.ts
- app/features/receive/receive-cashu-token-hooks.tsx
Fixes bugs with cross account claims within the same mint. We were trying to do a swap if the mint urls matched, but we were not checking the currencies
> fix: perform mint melt when same mint and different currency

- app/features/agicash-db/database.ts
- app/features/agicash-db/supabase-session-store.ts
- app/features/user/auth.ts
- app/features/wallet/wallet.tsx
- app/lib/supabase/supabase-realtime.ts
In this approach I am managing reconnection manually. What we do now is:
- when app goes to background, if the error doesn't happen with connection we manually unsubscribe it after 10 minutes (I think in practice error will happen lot sooner)
- when the error (or timeout does happen) if the app is in background we do nothing and if it is in foreground we try to reconnect up to 3 times
- when the app comes to foregorund we subscribe again
I also found out that you can't just wait for status subscribed and consider the connection to be established. that means that the socket is established but to know when the subscription is established for postgres_changes we have to listen for a system message of that type
> Fix Supabase realtime reconnection issues

- app/features/receive/cashu-receive-quote-hooks.ts
- app/features/receive/cashu-receive-quote-service.ts
- app/features/receive/cashu-token-swap-hooks.ts
- app/features/receive/cashu-token-swap-service.ts
- app/features/send/cashu-send-quote-hooks.ts
- app/features/send/cashu-send-swap-hooks.ts
This is temporary improvement for self resolution of concurrency errors. It's a pretty dumb approach where it just retries and uses the latest data on each retry. All mutations were set to use 3 retries.
Proper solution will most likely use queues to make sure operations for single account are never executed in parallel, plus it will have better retries were num of retries will depend on type of the error (e.g. concurrency error should probably be retried until it resolves and shouldn't even increment the attempt counter). Also irrecoverable errors should fail without retries and move the related entity to error state which would then be displayed somewhere (e.g. on history page where user could do manual intervention to retry maybe or undo the action and recover reserved proofs).
> Concurrency improvements - lightning transactions

- app/features/contacts/add-contact-drawer.tsx
- app/features/send/send-input.tsx
using `dvh` only considers the visible space so when a software keyboard pops up the total `dvh` decreases and would move the drawer up. Using `vh` allows us to maintian a fixed total height that includes the space under the keyboard.
This PR makes the drawer height fixed even when a keyboard is openeed
https://github.com/user-attachments/assets/82817749-fdf1-4c67-a18d-13e46718ebfe
> fix drawer height to account for software keyboard

- app/features/settings/settings.tsx
- app/features/settings/ui/settings-nav-button.tsx
removing padding from the left of the button messed up the active state for the button so we decided to just revert the change I made in #544
> indent settings nav buttons to fix highlight

- app/features/receive/cashu-receive-quote-repository.ts
- app/features/receive/cashu-token-swap-repository.ts
- app/features/send/cashu-send-quote-hooks.ts
- app/features/send/cashu-send-quote-repository.ts
- app/features/send/cashu-send-quote-service.ts
- app/features/send/cashu-send-swap-repository.ts
- app/features/send/send-confirmation.tsx
- app/features/send/send-store.ts
- app/features/transactions/transaction-details.tsx
- app/features/transactions/transaction-list.tsx
- app/features/transactions/transaction-repository.ts
- app/features/transactions/transaction.ts
- app/routes/_protected.send.confirm.tsx
When sending to contact or lightning address we now store the contact id or lightning address in the transaction details.
For now this is just used to show a user icon in the transaction list if the transaction was to a contact.
Alternative approach is here #552
> store transaction destination details

- supabase/migrations/20250815170919_unique-quote-ids.sql
closes #582 
It seems that somehow multiple send quotes are being created with the same melt quote ID. This should not happen because a melt quote can only be paid once, so we don't want to try to pay it twice. I can not figure out how two quotes are being created, but my guess is that the first call to `initiateSend` from `useInitiateCashuSendQuote` successfully triggers the quote creation, but then the mutation retries maybe because of a network error. Retrying the mutation creates another send with new proofs to send. 
I added unique constraints to mint and melt quote IDs because there should only be one record in our db per quote. This is only half of the solution as it does not fix whatever is causing the call to create a send quote happen twice, but at least now we won't end up with …
> add unique constraint on quote ids

- app/lib/supabase/supabase-realtime.ts
I haven't been able to reproduce the realtime error except for once while I was driving. However I noticed in the sentry logs that I don't see the "Retrying subscription after..." log and then in the realtime hook we only reset the retry count once fully connected. My suspicion is that if errors had happened before then the retry count was still incremented.
I'm not sure if this fixes the problem completely or not, but it seems like a reasonable change either way because when these statuses change we should have a fresh start
> reset retryCount on visibility/online change

- app/lib/supabase/supabase-realtime-channel.ts
- app/lib/supabase/supabase-realtime-hooks.ts
- app/lib/supabase/supabase-realtime-manager.ts
This fixes two bugs:
1. when channel error or timeout would happen on subscribed channel the retries wouldn't work because the status of the channel would still be subscribed and loop in processResubscribeQueue has this code:
```
if (!state || state.status === 'subscribed') {
break;
}
```
this was fixed by introducing reconnecting status and moving to that when resubscribe is scheduled.
2. when useSupabaseRealtime would be mounted, unmounted and the mounted again in the short period of time for the same channel topic (like in react strict mode) we would mess up the channel because current version of useEffect doesn't synchronise to setup and cleanup for the same topic in any way. in this pr we introduce synchronisation via global maps that stores pending setup and cleanup promises maps. …
> Realtime fixes and improvements
